export const LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE";
export const LOGIN_WITH_USERNAME_PASSWORD = "LOGIN_WITH_USERNAME_PASSWORD";

export const ONE_HOUR = 60 * 60;
export const ONE_DAY = 60 * 60 * 24;
export const ONE_WEEK = ONE_DAY * 7;

export const ADMIN_ROLE = "ADMIN_ROLE";
export const USER_ROLE = "USER_ROLE";

export default {
  LOGIN_WITH_GOOGLE,
  LOGIN_WITH_USERNAME_PASSWORD,
  ONE_HOUR,
  ONE_DAY,
  ONE_WEEK,
  ADMIN_ROLE,
  USER_ROLE,
};
