export const LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE";
export const LOGIN_WITH_USERNAME_PASSWORD = "LOGIN_WITH_USERNAME_PASSWORD";

export const ONE_HOUR = 60 * 60;
export const ONE_DAY = 60 * 60 * 24;
export const ONE_WEEK = ONE_DAY * 7;

export const ADMIN_ROLE = "ADMIN";
export const STUDENT_ROLE = "STUDENT";
export const TEACHER_ROLE = "TEACHER";

export const EXISTED_ERROR_CODE = "EXISTED_ERROR_CODE";

export const ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND";
export const WRONG_PASSWORD = "WRONG_PASSWORD";

export const TOKEN_IS_INVALID = "TOKEN_IS_INVALID";
